### ISSUE TITLE
Error Install in HassIO

### ISSUE THREAD

**Issue by zbuh** [rgruebel/ha_zigbee2mqtt_networkmap#20]
When trying to install in Hassio I get this error (log):

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_protocol.py", line 418, in start
    resp = await task
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_app.py", line 458, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/real_ip.py", line 33, in real_ip_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 67, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 216, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 115, in handle
    result = await result
  File "/config/custom_components/hacs/http.py", line 47, in get
    response = await response.response(self)
  File "/config/custom_components/hacs/http.py", line 167, in response
    repository = self.store.repositories[str(self.repository_id)]
KeyError: 'map.gif'
```

The files seem to copied tough.

**Comment by talondnb** [comment]
I thought it was just me.

```
Tue Jul 23 2019 16:59:56 GMT+0800 (AWST)

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_protocol.py", line 418, in start
    resp = await task
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_app.py", line 458, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/real_ip.py", line 33, in real_ip_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 67, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 216, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 115, in handle
    result = await result
  File "/config/custom_components/hacs/http.py", line 47, in get
    response = await response.response(self)
  File "/config/custom_components/hacs/http.py", line 167, in response
    repository = self.store.repositories[str(self.repository_id)]
KeyError: 'map.gif'
```

**Comment by rgruebel** [comment]
This is a HACS bug when displaying info.md with images. I have removed the image map.gif from info.md.
