### ISSUE TITLE
Error with graph update, try reloading this page or HASS

### ISSUE THREAD

**Issue by ps1x** [rgruebel/ha_zigbee2mqtt_networkmap#45]
After clicking on update map i get:
Error with graph update, try reloading this page or HASS

In home assistant logs i get:
```
websocket_api script: Error executing script. Unexpected error for call_service at pos 1: async_publish() missing 1 required positional argument: 'payload'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 381, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 584, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1495, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1530, in _execute_service
    await handler.job.target(service_call)
  File "/config/custom_components/zigbee2mqtt_networkmap/__init__.py", line 91, in update_service
    mqtt.async_publish(topic+'/bridge/networkmap/routes', 'graphviz')
TypeError: async_publish() missing 1 required positional argument: 'payload'
```
Home Assistant 2021.12.4
zigbee2mqtt_networkmap is latest version installed through HACS

**Comment by boc-the-git** [comment]
This is already reported including a fix (wish I'd seen that before fixing it myself locally!!): https://github.com/rgruebel/ha_zigbee2mqtt_networkmap/issues/42 

https://github.com/rgruebel/ha_zigbee2mqtt_networkmap/pull/44

**Comment by kevincaradant** [comment]
Hi @rgruebel 

Is there a way that you take into account this ? Via the PR ? 

Thank you ,)
